### ISSUE TITLE
Enhancement: Allow for schema extension

### ISSUE THREAD

**Issue by GregDomjan** [bmatthews68/ldapunit#3]
It appears [UnboundID is not supporting changing the In Memory server schema once started](https://docs.ldap.com/ldap-sdk/docs/in-memory-directory-server.html)

> It does not provide the ability to make changes to the configuration or schema while the server is running. The configuration and schema (if a schema is to be used) must be defined before the server is started. 

Would it be possible to enhance ldapunit to allow for schema extensions?

perhaps extend DirectoryServerConfiguration to include a location for schemaFiles

Addition to DirectoryServerUtils.startServer
Before server.startListening  include something like 
  config.setSchema(Schema.mergeSchemas(Schema.getDefaultStandardSchema(),
          Schema.getSchema(schemaFiles)));

**Comment by bmatthews68** [comment]
The feature has been implemented in version 2.1.0
